/**
 * Generated by Lovrabet CLI
 *
 * 这个文件包含了项目的模型配置，并自动注册到 SDK 中
 * CLI 工具会自动维护这个文件，通常不需要手动修改
 */

import { registerModels, CONFIG_NAMES, type ModelsConfig } from "@lovrabet/sdk";

export const LOVRABET_APP_CODE = "app-c4c89304";

/**
 * 项目的模型配置
 * 包含所有数据表的映射关系
 */
export const LOVRABET_MODELS_CONFIG: ModelsConfig = {
  appCode: LOVRABET_APP_CODE,
  models: {
    // ProjectMembers: {
    //   tableName: "project_members",
    //   datasetId: "71494bcba13f4ec7858abe90794183ad",
    // },
    Requirements: {
      tableName: "requirements",
      datasetId: "d26ed512e878461ca97d287a47606fd3",
    },
    Projects: {
      tableName: "projects",
      datasetId: "c6e55d6720b84ffcb21698b0a04ccd23",
    },
    Iterations: {
      tableName: "iterations",
      datasetId: "a60f11c17c5344e7a26d5144212cf366",
    },
    RequirementTypes: {
      tableName: "requirement_types",
      datasetId: "f17f1ee941c1468e87e6a0ca655ce00e",
    },
    CustomerInterviews: {
      tableName: "dataset_3c23",
      datasetId: "3ff202af07164d0a9c5df7ddd8f83c23",
    },
  }
} as const;

/**
 * 自动注册默认配置
 * 这样 createClient() 就可以无参数调用
 */
registerModels(LOVRABET_MODELS_CONFIG, CONFIG_NAMES.DEFAULT);

/**
 * 如果需要支持多项目或多环境，可以注册额外的配置：
 *
 * // 开发环境配置
 * registerModels({
 *   appCode: 'app-dev-123',
 *   models: { ... }
 * }, 'dev');
 *
 * // 其他项目配置
 * registerModels({
 *   appCode: 'other-project',
 *   models: { ... }
 * }, 'project-b');
 */
