/**
 * Generated by Lovrabet CLI
 */

import { createClient } from "@lovrabet/sdk";

export const LOVRABET_APP_CODE = "app-c4c89304";

// 创建新的客户端实例
export const client = createClient({
  appCode: LOVRABET_APP_CODE,
  env: 'online',

  // 实体配置
  entities: {
    ProjectMembers: {
      tableName: "project_members",
      datasetId: "71494bcba13f4ec7858abe90794183ad",
    },
    Requirements: {
      tableName: "requirements",
      datasetId: "d26ed512e878461ca97d287a47606fd3",
    },
    Projects: {
      tableName: "projects",
      datasetId: "c6e55d6720b84ffcb21698b0a04ccd23",
    },
    Iterations: {
      tableName: "iterations",
      datasetId: "a60f11c17c5344e7a26d5144212cf366",
    },
    RequirementTypes: {
      tableName: "requirement_types",
      datasetId: "f17f1ee941c1468e87e6a0ca655ce00e",
    },
    CustomerInterviews: {
      tableName: "dataset_3ff202af07164d0a9c5df7ddd8f83c23",
      datasetId: "3ff202af07164d0a9c5df7ddd8f83c23",
    },
  },

  options: {
    onError: (error: any) => {
      console.error('API Error:', error);
    }
  }
});

// 向后兼容的模型导出（保持旧代码可以工作）
export const models = {
  projectMembers: client.entities.ProjectMembers,
  requirements: client.entities.Requirements,
  projects: client.entities.Projects,
  iterations: client.entities.Iterations,
  requirementTypes: client.entities.RequirementTypes,
  customerInterviews: client.entities.CustomerInterviews,
};
