/**
 * Generated by Lovrabet CLI
 * Created: 2025-12-30T11:26:52.194Z
 *
 * 这个文件包含了项目的模型配置，并自动注册到 SDK 中
 * CLI 工具会自动维护这个文件，通常不需要手动修改
 */

import { registerModels, CONFIG_NAMES, type ModelsConfig } from "@lovrabet/sdk";

export const LOVRABET_APP_CODE = "app-c4c89304";

/**
 * 项目的模型配置
 * 使用数组格式，每个模型包含 datasetCode、tableName、name 和可选的 alias
 *
 * 访问方式：
 * - 标准访问：client.models.dataset_[datasetCode]
 * - 别名访问：client.models.[alias]（如果配置了 alias）
 */
export const LOVRABET_MODELS_CONFIG: ModelsConfig = {
  appCode: LOVRABET_APP_CODE,
  models: [
    {
      datasetCode: "3ff202af07164d0a9c5df7ddd8f83c23",
      tableName: "dataset_f83c23",
      name: "客户访谈记录",
      alias: "datasetF83c23",
    },
    {
      datasetCode: "a60f11c17c5344e7a26d5144212cf366",
      tableName: "iterations",
      name: "迭代信息",
      alias: "iterations",
    },
    {
      datasetCode: "d26ed512e878461ca97d287a47606fd3",
      tableName: "requirements",
      name: "需求",
      alias: "requirements",
    },
    {
      datasetCode: "f17f1ee941c1468e87e6a0ca655ce00e",
      tableName: "requirement_types",
      name: "需求类型",
      alias: "requirementTypes",
    },
    {
      datasetCode: "c6e55d6720b84ffcb21698b0a04ccd23",
      tableName: "projects",
      name: "项目",
      alias: "projects",
    },
    {
      datasetCode: "71494bcba13f4ec7858abe90794183ad",
      tableName: "project_members",
      name: "项目成员",
      alias: "projectMembers",
    },
  ],
} as const;

/**
 * 自动注册配置
 * 配置名称: CONFIG_NAMES.DEFAULT
 */
registerModels(LOVRABET_MODELS_CONFIG, CONFIG_NAMES.DEFAULT);

/**
 * 如果需要支持多项目或多环境，可以注册额外的配置：
 *
 * // 开发环境配置
 * registerModels({
 *   appCode: 'app-dev-123',
 *   models: [...]
 * }, 'dev');
 *
 * // 其他项目配置
 * registerModels({
 *   appCode: 'other-project',
 *   models: [...]
 * }, 'project-b');
 */
