/**
 * Lovrabet SDK 客户端实例
 * Generated by Rabetbase CLI
 * Created: 2026-01-16T10:07:17.967Z
 *
 * 这个文件负责创建和导出统一的客户端实例，供整个应用使用
 * 通过导入 './api' 文件来自动执行配置注册
 */

import { createClient, CONFIG_NAMES } from "@lovrabet/sdk";
import "./api"; // 导入配置文件，执行 registerModels() 注册
import { LOVRABET_SDK_CONFIG } from "./sdk-config";

/**
 * 主要的客户端实例
 */
export const lovrabetClient = createClient({
  apiConfigName: CONFIG_NAMES.DEFAULT,
  ...LOVRABET_SDK_CONFIG,
});

/**
 * 使用示例：
 *
 * // 在组件中使用
 * import { lovrabetClient } from '@/api/client';
 *
 * // 查看当前可用模型
 * const models = lovrabetClient.getModelList();
 *
 * // 运行 `rabetbase api pull` 后，按生成的模型别名调用：
 * // const data = await lovrabetClient.models.requirements.filter({
 * //   currentPage: 1,
 * //   pageSize: 20
 * // });
 *
 * 浏览器子应用默认走登录态 Cookie，无需在此文件写入 accessKey / token；
 * 需要服务端 accessKey / OpenAPI token 的用法见 SDK 文档与 skill guides。
 */
